#use_frameworks!

source 'https://github.com/ioszhanghui/GMPublicRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'GMDataTool_Example' do
  pod 'GMDataTool', :path => '../'

  target 'GMDataTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
