use_frameworks!

platform :ios, '8.0'

target 'GMDataTool_Example' do
  pod 'GMDataTool', :path => '../'

  target 'GMDataTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
